# Generated by Django 4.2 on 2024-09-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='categories',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
