# Generated by Django 4.2 on 2024-09-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_reviewrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='content_file',
            field=models.FileField(blank=True, null=True, upload_to='submission_files/'),
        ),
    ]
